using Augur.Domain.Common;
using Augur.Domain.Enums;

namespace Augur.Domain.Entities;

/// <summary>
/// Represents a mapping from a source control (in one framework) to a target control in another framework.
/// Enables "test once, comply many" by linking equivalent controls across frameworks.
/// </summary>
public sealed class ControlMapping : Entity
{
    public Guid SourceControlId { get; private set; }
    public ComplianceFramework SourceFramework { get; private set; }
    public string SourceControlCode { get; private set; }

    public ComplianceFramework TargetFramework { get; private set; }
    public string TargetControlCode { get; private set; }
    public string TargetControlTitle { get; private set; }

    /// <summary>Confidence score 0-100 indicating mapping strength.</summary>
    public int ConfidenceScore { get; private set; }

    /// <summary>Mapping rationale for audit trail.</summary>
    public string Rationale { get; private set; }

    /// <summary>Whether this mapping was auto-generated or manually curated.</summary>
    public bool IsAutoGenerated { get; private set; }

    private ControlMapping()
    {
        SourceControlCode = string.Empty;
        TargetControlCode = string.Empty;
        TargetControlTitle = string.Empty;
        Rationale = string.Empty;
    }

    public ControlMapping(
        Guid sourceControlId,
        ComplianceFramework sourceFramework,
        string sourceControlCode,
        ComplianceFramework targetFramework,
        string targetControlCode,
        string targetControlTitle,
        int confidenceScore,
        string rationale,
        bool isAutoGenerated)
    {
        SourceControlId = sourceControlId;
        SourceFramework = sourceFramework;
        SourceControlCode = sourceControlCode.Trim();
        TargetFramework = targetFramework;
        TargetControlCode = targetControlCode.Trim();
        TargetControlTitle = targetControlTitle.Trim();
        ConfidenceScore = Math.Clamp(confidenceScore, 0, 100);
        Rationale = rationale.Trim();
        IsAutoGenerated = isAutoGenerated;
    }

    public static ControlMapping Create(
        Guid sourceControlId,
        ComplianceFramework sourceFramework,
        string sourceControlCode,
        ComplianceFramework targetFramework,
        string targetControlCode,
        string targetControlTitle,
        int confidenceScore,
        string rationale,
        bool isAutoGenerated = true)
    {
        if (sourceFramework == targetFramework)
            throw new ArgumentException("Source and target frameworks must differ.", nameof(targetFramework));

        if (string.IsNullOrWhiteSpace(sourceControlCode))
            throw new ArgumentException("Source control code is required.", nameof(sourceControlCode));

        if (string.IsNullOrWhiteSpace(targetControlCode))
            throw new ArgumentException("Target control code is required.", nameof(targetControlCode));

        if (string.IsNullOrWhiteSpace(targetControlTitle))
            throw new ArgumentException("Target control title is required.", nameof(targetControlTitle));

        if (string.IsNullOrWhiteSpace(rationale))
            throw new ArgumentException("Mapping rationale is required.", nameof(rationale));

        return new ControlMapping(
            sourceControlId,
            sourceFramework,
            sourceControlCode,
            targetFramework,
            targetControlCode,
            targetControlTitle,
            confidenceScore,
            rationale,
            isAutoGenerated);
    }

    public void UpdateConfidence(int newScore, string updatedRationale)
    {
        ConfidenceScore = Math.Clamp(newScore, 0, 100);
        Rationale = updatedRationale.Trim();
        Touch();
    }

    public void MarkAsCurated()
    {
        IsAutoGenerated = false;
        Touch();
    }
}
