using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Augur.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddControlMapping : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ControlMappings",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    SourceControlId = table.Column<Guid>(type: "uuid", nullable: false),
                    SourceFramework = table.Column<int>(type: "integer", nullable: false),
                    SourceControlCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    TargetFramework = table.Column<int>(type: "integer", nullable: false),
                    TargetControlCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    TargetControlTitle = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    ConfidenceScore = table.Column<int>(type: "integer", nullable: false),
                    Rationale = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ControlMappings", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ControlMappings_SourceControlId_TargetFramework",
                table: "ControlMappings",
                columns: new[] { "SourceControlId", "TargetFramework" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ControlMappings");
        }
    }
}
